// eslint-disable-next-line
import React, {Component} from 'react';
import 'react-fontawesome';

class FAQ extends Component {

    render() {
        const location = this.props.location;
        let answerClass = "";
        let React = require('react');
        let FontAwesome = require('react-fontawesome');

        const answers = [{
            currentLocation: "Alabama",
            level: "red",
            intent: "Submit to local public school superintendent (form provided by superintendent) ",
            intentLink: "",
            withdrawal: "Same as notice of intent ",
            withdrawalLink: "",
            testing: "High school graduation examinations available, though not required (Contact local district) ",
            testingLink: "",
            certification: "Certification required (Church schools exempt) ",
            certificationLink: "",
            age: "7-16 ",
            ageLink: "",
            attendance: "140 days per year ",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day ",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included. Private schools must include P.E. ",
            subjectsLink: "",
            curriculum: "Not regulated ",
            curriculumLink: "",
            records: "Records of work that includes attendance and hours of instruction ",
            recordsLink: "https://www2.ed.gov/about/offices/list/oii/nonpublic/alabama.html"
        },
        {
            currentLocation: "Alaska",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "Not regulated. ",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Arizona",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Arkansas",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "California",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Colorado",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Connecticut",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Delaware",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Florida",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Georgia",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Hawaii",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Idaho",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Illinois",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Indiana",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Iowa",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Kansas",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Kentucky",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Louisiana",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Maine",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Maryland",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Massachusetts",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Michigan",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Minnesota",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Mississippi",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Missouri",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Montana",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Nebraska",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Nevada",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "New Hampshire",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "New Jersey",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "New Mexico",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "New York",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "North Carolina",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "North Dakota",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Ohio",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Oklahoma",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Oregon",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Pennsylvania",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Rhode Island",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "South Carolina",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "South Dakota",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Tennessee",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Texas",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Utah",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Vermont",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Virginia",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Washington",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "West Virginia",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Wisconsin",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        },
        {
            currentLocation: "Wyoming",
            level: " ",
            intent: "None required",
            intentLink: "",
            withdrawal: "Yeppers",
            withdrawalLink: "",
            testing: "None required",
            testingLink: "",
            certification: "Certification required (Church schools exempt)",
            certificationLink: "",
            age: "7-16",
            ageLink: "",
            attendance: "140 days per year",
            attendanceLink: "",
            yearlyHrs: "Between 8:00 a.m. and 4 p.m. for a minimum of three hours per day",
            yearlyHrsLink: "",
            subjects: "State mandated subjects must be included ",
            subjectsLink: "",
            curriculum: "Not regulated",
            curriculumLink: "",
            records: "Keep records. ",
            recordsLink: ""
        }
        ];

        let newAnswers =
            {
                currentLocation: "Choose State",
                level: "",
                intent: "",
                intentLink: "",
                withdrawal: "",
                withdrawalLink: "",
                testing: "",
                testingLink: "",
                certification: "",
                certificationLink: "",
                age: "",
                ageLink: "",
                attendance: "",
                attendanceLink: "",
                yearlyHrs: "",
                yearlyHrsLink: "",
                subjects: "",
                subjectsLink: "",
                curriculum: "",
                curriculumLink: "",
                records: "",
                recordsLink: ""
            };

        function handleChange() {
            for (let i = 0; i < answers.length; i++) {
                if (answers[i].currentLocation === location) {
                    newAnswers.currentLocation = answers[i].currentLocation;
                    newAnswers.level = answers[i].level;
                    newAnswers.intent = answers[i].intent;
                    newAnswers.intentLink = answers[i].intentLink;
                    newAnswers.withdrawal = answers[i].withdrawal;
                    newAnswers.withdrawalLink = answers[i].withdrawalLink;
                    newAnswers.testing = answers[i].testing;
                    newAnswers.testingLink = answers[i].testingLink;
                    newAnswers.certification = answers[i].certification;
                    newAnswers.certificationLink = answers[i].certificationLink;
                    newAnswers.age = answers[i].age;
                    newAnswers.ageLink = answers[i].ageLink;
                    newAnswers.attendance = answers[i].attendance;
                    newAnswers.attendanceLink = answers[i].attendanceLink;
                    newAnswers.yearlyHrs = answers[i].yearlyHrs;
                    newAnswers.yearlyHrsLink = answers[i].yearlyHrsLink;
                    newAnswers.subjects = answers[i].subjects;
                    newAnswers.subjectsLink = answers[i].subjectsLink;
                    newAnswers.curriculum = answers[i].curriculum;
                    newAnswers.curriculumLink = answers[i].curriculumLink;
                    newAnswers.records = answers[i].records;
                    newAnswers.recordsLink = answers[i].recordsLink;
                    newAnswers.linkText = answers[i].linkText;
                }
                if (newAnswers.currentLocation === "Choose State") {
                    answerClass = "blank"
                }
                else {
                    answerClass = "answer"
                }
            }
        }

        let icon = <FontAwesome className="fa fa-info-circle faq-icon" aria-hidden="true"/>;

        return (
            <div>
                <div className="col-xs-12 col-md-6 faq-col">
                    <ul onChange={handleChange()}>
                        <li className="question">Notice of intent required?</li>
                        <li className={answerClass}>{newAnswers.currentLocation === "Choose State" ? "?" : newAnswers.intent} <a href={newAnswers.intentLink} target="_blank" rel="noopener">{newAnswers.intentLink === "" ? "" : icon}</a></li>
                        <li className="question">Public school withdrawal required?</li>
                        <li className={answerClass}>{newAnswers.currentLocation === "Choose State" ? "?" : newAnswers.withdrawal} <a href={newAnswers.withdrawalLink} target="_blank" rel="noopener">{newAnswers.withdrawalLink === "" ? "" : icon}</a></li>
                        <li className="question">Testing required?</li>
                        <li className={answerClass}>{newAnswers.currentLocation === "Choose State" ? "?" : newAnswers.testing} <a href={newAnswers.testingLink} target="_blank" rel="noopener">{newAnswers.testingLink === "" ? "" : icon}</a></li>
                        <li className="question">Teacher certification required?</li>
                        <li className={answerClass}>{newAnswers.currentLocation === "Choose State" ? "?" : newAnswers.certification} <a href={newAnswers.certificationLink} target="_blank" rel="noopener">{newAnswers.certificationLink === "" ? "" : icon}</a></li>
                        <li className="question">Age requirements?</li>
                        <li className={answerClass}>{newAnswers.currentLocation === "Choose State" ? "?" : newAnswers.age} <a href={newAnswers.ageLink} target="_blank" rel="noopener">{newAnswers.ageLink === "" ? "" : icon}</a></li>
                    </ul>
                </div>
                <div className="col-xs-12 col-md-6 faq-col">
                    <ul onChange={handleChange()}>
                        <li className="question">Attendance requirements?</li>
                        <li className={answerClass}>{newAnswers.currentLocation === "Choose State" ? "?" : newAnswers.attendance} <a href={newAnswers.attendanceLink} target="_blank" rel="noopener">{newAnswers.attendanceLink === "" ? "" : icon}</a></li>
                        <li className="question">Hours required per year?</li>
                        <li className={answerClass}>{newAnswers.currentLocation === "Choose State" ? "?" : newAnswers.yearlyHrs} <a href={newAnswers.yearlyHrsLink} target="_blank" rel="noopener">{newAnswers.yearlyHrsLink === "" ? "" : icon}</a></li>
                        <li className="question">Subjects required?</li>
                        <li className={answerClass}>{newAnswers.currentLocation === "Choose State" ? "?" : newAnswers.subjects} <a href={newAnswers.subjectsLink} target="_blank" rel="noopener">{newAnswers.subjectsLink === "" ? "" : icon}</a></li>
                        <li className="question">Curriculum required?</li>
                        <li className={answerClass}>{newAnswers.currentLocation === "Choose State" ? "?" : newAnswers.curriculum} <a href={newAnswers.curriculumLink} target="_blank" rel="noopener">{newAnswers.curriculumLink === "" ? "" : icon}</a></li>
                        <li className="question">Records to keep?</li>
                        <li className={answerClass}>{newAnswers.currentLocation === "Choose State" ? "?" : newAnswers.records} <a href={newAnswers.recordsLink} target="_blank" rel="noopener">{newAnswers.recordsLink === "" ? "" : icon}</a></li>
                    </ul>
                    {console.log(newAnswers.recordsLink)}
                </div>
            </div>
        );
    }
}


export default FAQ;